version: '2'

services:
  java-web-services:
    image: bjcp:latest
    container_name: bjcp
    command: /usr/local/tomcat/bin/catalina.sh run
    ports:
      - '8080:8080'
      - '5000:5000'
      - '10483:10483'
    environment:
      MY_ENVE: "myEnvValue"
      JAVA_OPTS: "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,address=5000,suspend=n -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=10483 -Dcom.sun.management.jmxremote.rmi.port=10483 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Djava.rmi.server.hostname=localhost"
    networks:
      localbridge:
        aliases:
          - bjcp
    extra_hosts:
      - "localhost.eventhorizon.com.br:127.0.0.1"
    volumes:
      # CATALINA_OPTS via setenv.sh
#      - ./setenv.sh:/opt/tomcat/bin/setenv.sh

      # War files
      - ../bjcp-2015/target/bjcp-2015.war:/usr/local/tomcat/webapps/bjcp-2015.war

networks:
  localbridge:
    driver: bridge
